# GoReleaser-based Taskfile
version: '3'

# Enable .env file loading
dotenv: ['.env']

vars:
  # Repository and environment configuration
  REPO_OWNER: "muthuishere"
  REPO_NAME: "lnb"
  GITHUB_REPO: "{{.REPO_OWNER}}/{{.REPO_NAME}}"
  GITHUB_SECRET_ENVIRONMENT: "dev"
  
  # Use APP_NAME from .env as BIN_NAME for backward compatibility
  BIN_NAME: "lnb"
  # Release version - read from versions.txt (single source of truth)
  RELEASE_VERSION:
    sh: cat versions.txt

tasks:
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist
      - mkdir -p dist

  build:
    desc: Build for current platform
    cmds:
      - go build -o dist/{{.BIN_NAME}} ./cmd/lnb

  build:all:
    desc: Build for all platforms using GoReleaser
    cmds:
      - goreleaser build --clean --snapshot

  test:build:
    desc: Build test binary for integration tests
    cmds:
      - go build -o dist/test-lnb ./cmd/lnb

  test:integration:
    desc: Run integration tests using Go unit tests
    deps: [test:build]
    cmds:
      - cd cmd/lnb && go test -v -run TestLnbIntegration

  test:unit:
    desc: Run only the main_test.go unit tests
    deps: [test:build]
    cmds:
      - cd cmd/lnb && go test -v -run TestLnb

  test:all:
    desc: Run all tests (unit and integration)
    cmds:
      - task: test:unit
      - task: test:integration


  install:
    desc: Install LNB locally
    deps: [build:all]
    cmds:
      - task: build
      - ./dist/{{.BIN_NAME}} ./dist/{{.BIN_NAME}} install

  remove:
    desc: Remove LNB from local system
    cmds:
      - task: build
      - ./dist/{{.BIN_NAME}} ./dist/{{.BIN_NAME}} remove
      - rm -rf /usr/local/bin/lnb


  # GoReleaser commands
  check:
    desc: Check GoReleaser configuration
    cmds:
      - goreleaser check


  version:
    desc: Show current version
    cmds:
      - |
        echo "Current version: {{.RELEASE_VERSION}}"
        echo "From file: versions.txt"



  # Release Management (Go-based, no shell scripts)
  release:
    desc: Push commits and current tag to origin to trigger automatic GitHub Actions release
    cmds:
      - |
        echo "🚀 Pushing to GitHub..."
        echo "📤 Pushing commits..."
        git push origin main
        if ! git rev-parse "v{{.RELEASE_VERSION}}" >/dev/null 2>&1; then
          echo "🔖 Creating tag v{{.RELEASE_VERSION}}..."
          git tag v{{.RELEASE_VERSION}}
        else
          echo "🔖 Tag v{{.RELEASE_VERSION}} already exists."
        fi
        echo "📤 Pushing current tag v{{.RELEASE_VERSION}}..."
        git push origin v{{.RELEASE_VERSION}}
        echo "✅ Commits and tag pushed!"
        echo ""
        echo "🚀 GitHub Actions will automatically trigger the release workflow"
        git checkout main

  setup:npm-publisher:
    desc: Install goreleaser-npm-publisher globally
    cmds:
      - |
        if ! command -v goreleaser-npm-publisher &> /dev/null; then
          echo "📦 Installing @muthuishere/goreleaser-npm-publisher..."
          npm install -g @muthuishere/goreleaser-npm-publisher
        else
          echo "✅ goreleaser-npm-publisher already installed"
        fi

  publish:
    desc: Publish to GitHub and NPM (used by both local and CI)
    deps: [build:all, setup:npm-publisher]
    cmds:
      - |
        echo "🚀 Running release with GoReleaser..."
        export GITHUB_TOKEN="{{.GORELEASER_GITHUB_TOKEN}}"
        goreleaser release --clean
      - |
        echo "📦 Building NPM package..."
        goreleaser-npm-publisher build
      - |
        echo "📦 Publishing to NPM..."
        goreleaser-npm-publisher publish --clean --token {{.NPM_TOKEN}}

  publish-local:
    desc: Publish locally with proper git tag alignment
    deps: [build:all, setup:npm-publisher]
    cmds:
      - |
        echo "🏷️  Preparing local release for version {{.RELEASE_VERSION}}..."
        
        # Ensure we're on main and up to date
        echo "📍 Ensuring clean git state..."
        git checkout main
        
        # Check if tag exists locally, if not create it
        if ! git rev-parse "v{{.RELEASE_VERSION}}" >/dev/null 2>&1; then
          echo "🔖 Creating local tag v{{.RELEASE_VERSION}} for current commit..."
          git tag v{{.RELEASE_VERSION}}
        else
          echo "🔖 Tag v{{.RELEASE_VERSION}} already exists locally"
          
          # Check if current commit matches the tag
          CURRENT_COMMIT=$(git rev-parse HEAD)
          TAG_COMMIT=$(git rev-parse "v{{.RELEASE_VERSION}}")
          
          if [ "$CURRENT_COMMIT" != "$TAG_COMMIT" ]; then
            echo "⚠️  Current commit ($CURRENT_COMMIT) doesn't match tag commit ($TAG_COMMIT)"
            echo "🔄 Re-tagging current commit as v{{.RELEASE_VERSION}}..."
            git tag -d v{{.RELEASE_VERSION}}
            git tag v{{.RELEASE_VERSION}}
          else
            echo "✅ Current commit matches tag commit"
          fi
        fi
        
        echo "🚀 Running local release with GoReleaser..."
        export GITHUB_TOKEN="{{.GORELEASER_GITHUB_TOKEN}}"
        goreleaser release --clean
      - |
        echo "📦 Building NPM package..."
        goreleaser-npm-publisher build
      - |
        echo "📦 Publishing to NPM..."
        goreleaser-npm-publisher publish --clean --token {{.NPM_TOKEN}}

  create-secrets:
    desc: Create GitHub secrets from .env file
    cmds:
      - |
        export GITHUB_REPO="{{.GITHUB_REPO}}"
        export GITHUB_ENVIRONMENT="{{.GITHUB_SECRET_ENVIRONMENT}}"
        go run secrets.go .env