# This file was generated by GoReleaser. DO NOT EDIT.
cask "lnb" do
  desc "A cross-platform utility that makes command-line tools accessible from anywhere by creating symbolic links or wrapper scripts in your system's PATH"
  homepage "https://github.com/muthuishere/lnb"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lnb"

  on_macos do
    on_intel do
      url "https://github.com/muthuishere/lnb/releases/download/v0.2.3/lnb_0.2.3_Darwin_x86_64.tar.gz"
      sha256 "ed16de9d9422b240625d313005ac137c9cab85e29f015da9e115377c24df6313"
    end
    on_arm do
      url "https://github.com/muthuishere/lnb/releases/download/v0.2.3/lnb_0.2.3_Darwin_arm64.tar.gz"
      sha256 "99a4ed9d5814d6fe4b65d5e6380746f5d06d3d020b16d2db320135aa93d8fdd4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/muthuishere/lnb/releases/download/v0.2.3/lnb_0.2.3_Linux_x86_64.tar.gz"
      sha256 "7516bc88caf85df97ea0c4668a37a4639e4ec753d5b152815f3e24d90ef3e40b"
    end
    on_arm do
      url "https://github.com/muthuishere/lnb/releases/download/v0.2.3/lnb_0.2.3_Linux_arm64.tar.gz"
      sha256 "6ff66e1d7a593751649aa39291e09c4286c63e91ee7f7f4075cac44aec11ea71"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lnb"]
    end
  end

  # No zap stanza required
end
