# This file is automatically generated by GoReleaser during the release process.
# Do not edit manually - your changes will be overwritten.

cask "lnb" do
  version "0.1.0"
  sha256 "abc123..." # This will be automatically filled by GoReleaser

  url "https://github.com/muthuishere/lnb/releases/download/v#{version}/lnb_#{version}_Darwin_x86_64.tar.gz",
      verified: "github.com/muthuishere/lnb/"
  name "LNB"
  desc "A cross-platform utility that makes command-line tools accessible from anywhere by creating symbolic links or wrapper scripts in your system's PATH"
  homepage "https://github.com/muthuishere/lnb"

  binary "lnb"

  postflight do
    # Remove macOS quarantine attribute if xattr is available
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lnb"]
    end
  end

  # Zap directive for complete uninstall
  zap trash: [
    "~/.lnb",
  ]
end
